apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: onboard-service
  title: Onboard Service Template
  description: Template to onboard a new service
  
spec:
  type: service
  path: ./template.yaml
  lifecycle: experimental
  owner: your-team
  
  

#run this command to register the template yarn backstage-cli catalog:import
